### ISSUE TITLE
/r/random sidebar is from a different random sub than the one displayed

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#1165]
Slide version: 70a60a0186e13709e5da2b8bc58f550dc14a13cf
Android version: 5.1.1

Edit: So the same would also be true for randnsfw

**Comment by dethstar** [comment]
The problem is [this](https://github.com/ccrama/Slide/blob/master/app/src/main/java/me/ccrama/redditslide/Activities/SubredditView.java#L647):
The string value is "random" and thus the app asks reddit for the sidebar to "random" sub and that's why it is different.

So that same issue happens [here](https://github.com/ccrama/Slide/blob/master/app/src/main/java/me/ccrama/redditslide/Activities/SubredditView.java#L457) when you ask for a different sort. 
Fix by simply getting the subreddit name from the posts on the onCreate method.

So doing
`subreddit = ((SubmissionsView) adapter.getCurrentFragment()).posts.subreddit;`
Unless that also takes it from that first variable. Then it should be something like:
`subreddit = ((SubmissionsView) adapter.getCurrentFragment()).posts.posts.get(0).getSubredditName();`
Before calling doSubSidebar(subreddit); Should work

Should be preserved somewhere though (maybe a flag). because I think refreshing should change the subreddit if it was random.

**Comment by Controless** [comment]
I don't think your code snippet will work for subreddits with 0 posts, right?

**Comment by dethstar** [comment]
I think the first snippet should, because it access the posts object that has a posts list.
The second one would def throw an exception for a subreddit with 0 posts.

**Comment by Controless** [comment]
In addition to this, when submitting to /r/random, the Subreddit edittext should be autofilled with the current random subreddit name.

**Comment by ccrama** [comment]
Fixed now!

**Comment by Controless** [comment]
I think this issue should be reopened, it seems like you fixed it for /r/random but not /r/randnsfw.

**Comment by ccrama** [comment]
Is randnsfw a thing? Haven't heard of that before

**Comment by Controless** [comment]
Yes, it basically opens up a random nsfw subreddit. I didn't now about it until a few weeks ago as well but it definitely is a thing.

**Comment by Alexendoo** [comment]
There's also /r/myrandom

**Comment by ccrama** [comment]
Added nsfwrandom and myrandom

**Comment by dpeukert** [comment]
Looks like this issue reappeared at some point.

Slide version: 6.2 (F-Droid)
Android version: Q Beta 5

**Comment by Alexendoo** [comment]
For which sub @dpeukert - e.g. random, nsfwrand, myrandom?

**Comment by dpeukert** [comment]
I was able to reproduce this with random and nsfwrand (myrandom seems to be
a Reddit Premium only feature).
