### ISSUE TITLE
Back button 2x choose new sub

### ISSUE THREAD

**Issue by slippertpete** [ccrama/Slide#1189]
I'd like to see a feature added so if I hit back button 2x it will show the left side menu to choose a new sub reddit

**Comment by Alexendoo** [comment]
I'm afraid it would be unreasonable for an app to redefine what the back button means to it, it's a standard action across android and should be predictable to those without even any knowledge of the app

**Comment by ccrama** [comment]
This would aid in the fact that you can't swipe anywhere to open the menu, might be possible in single mode (or as a choice in the back button option in Settings)

**Comment by slippertpete** [comment]
Other apps allow for 2 presses of the back button to complete a task  ex boost for Reddit   2 taps to exit

**Comment by Alexendoo** [comment]
That's to protect the user from accidentally closing, can be useful in reddit apps. Implementing a separate action would require delaying any back button press to determine if the user intended to use the single or double tap by a non trivial time frame. For instance standard timeframe for double clicks is 500ms, yet the app should respond to the user under 100ms or else there is a very noticeable delay

**Comment by Nxt3** [comment]
I'm closing this because this is poor UX. If you had this setting enabled, there would be no way to leave the app using the back button--something you're able to do in every other app. The solution to this could be to increase the drawer swipe margin--something I've already tried (and was unsuccessful in doing so)--but even then, this is a difficult task given how the drawer is handled; Google makes it hard to adjust these things because they simply don't want you overriding that behavior (of the drawer).
