### ISSUE TITLE
Request: easier way to reorder subs

### ISSUE THREAD

**Issue by kufii** [ccrama/Slide#1214]
when you're subscribed to a lot of subreddits, reordering them all is a massive pain. One of the most annoying issues is that when you subscribe to a new subreddit, it shows up at the end of the list, and I have to drag it to it's alphabetical position.

What I think would be a good way to do it would be to display them all in alphabetical order by default and then be able to search for and pin certain subreddits to the top. There might be some other good ways to go about it, but at the moment, managing the order of such a massive list is a huge pain

**Comment by ccrama** [comment]
Tap the submission and you have the option to move straight to top. You can also multi-select and move a bunch at once

**Comment by kufii** [comment]
honestly, just having it so that new subs show up in the alphabetical position or a quick way to move them into alphabetical position would be a huge help. The move straight to top is definitely nice though

**Comment by ccrama** [comment]
It's not really possible to do so without resetting the current dataset, though, so I cannot do that.

**Comment by Alexendoo** [comment]
With 510031b335bd22f1abb391a576aac9b1c15a05fa I've made it so if your list is already sorted, the new subreddit(s) are inserted into a sorted position also, otherwise append as it does currently.

This will be pretty good for most users who use a sorted list already, but it doesn't work around a partially altered order, I think in that case it's best to just append the items and let the user decide where they go
