### ISSUE TITLE
Content-type header on images is not accounted for

### ISSUE THREAD

**Issue by brentluna** [ccrama/Slide#1228]
Slide version: 5
Android version:
"I really didn't expect that to work!" 
https://reddit.com/r/funny/comments/4bj33y/i_really_didnt_expect_that_to_work/

The gif just stays a static image in the media player

**Comment by ccrama** [comment]
It appears to be a png but somehow a gif?

**Comment by brentgsw** [comment]
It would seems so. Had to open it on chrome to get it to play

**Comment by ccrama** [comment]
Doesn't work on Sync or Relay either

**Comment by brentgsw** [comment]
Well slide >sync/relay, so it should work here! They probably don't come up often, so probably not a priority.

**Comment by Alexendoo** [comment]
Is this not #443? The content-type header is displaying correctly as image/gif

**Comment by ccrama** [comment]
I check for animated jpegs as they are not usually used for images, and can therefore show png images much faster. Checking for animated pngs might not be worth it time wise considering how few are animated

**Comment by Alexendoo** [comment]
This post is a gif though, the issue is you're looking at the file extension when on imgur you can set it as anything it uses and it will serve the content, the content-type header, if present, should take precedence over any filename things.

http://i.imgur.com/9FhjtID.png
http://i.imgur.com/9FhjtID.jpg
http://i.imgur.com/9FhjtID.jpeg
http://i.imgur.com/9FhjtID.gif

Animated jpegs do not exist, animated APNGs are mostly unsupported (only works in ff + safari) on the web so can be completely ignored

**Comment by ccrama** [comment]
The issue with that is asking for the content type header is not instant and will cause "lag" in displaying png images, which are the vast majority of images on Reddit

**Comment by Alexendoo** [comment]
https://www.reddit.com/r/slideforreddit/comments/4dwc9d/gifs_not_loading_as_gifs/

This will also be pertinent to making i.reddituploads.com images work, as they never have a file type

**Comment by ccrama** [comment]
Done, now all images are checked
