### ISSUE TITLE
Post page top margin should be larger

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1597]
Slide version: 5.3.3-alpha.4
Android version: 6.0.1

![screenshot_20160427-142023](https://cloud.githubusercontent.com/assets/13410769/14868638/749c2570-0c83-11e6-9513-a620baab46c2.png)

**Comment by Nxt3** [comment]
I purposefully set this margin to be that height. It's consistent with the multicolumn layout this way. There isn't a way to affect one or the other--so this sacrifice had to be made. I don't think this is that big an issue. Truthfully, there just isn't a way to fix the margin inconsistencies with multicolumn's margins--and have the single column layout's margins look as perfect as I would like.

**Comment by Controless** [comment]
But a significant amount of people use this single column layout rather than multicolumn so shouldn't that be prioritized instead?

**Comment by Nxt3** [comment]
Well then what about people who use multicolumn? It's not even a big deal. I'm not too crazy about it--but if I don't have it like this, then people complain about the inconsistencies in multicolumn :|

**Comment by Controless** [comment]
I mean, it's better to appease a larger group of people than a much smaller subset. And how it is supposed to look in multicolumn mode? It still has the same small top margin, can you please screenshot yours?

**Comment by Nxt3** [comment]
Look at issue #1317. The way the margins were drawn on the top and bottom affected the larger space of the cards from everything below the toolbar. Ideally, there would be a top margin of 4dp for each card, and bottom margin of 4dp for each card; added up, that's 8dp between each card.

Unfortunately, in multicolumn, that top margin of the card is ignored. I'd have to manually set the toolbar's bottom margin to push the cards down further; this also doesn't work, because while it fixes the multicolumn--then there is much too large a gap between the top post and card in single column.

Believe me when I say I tried really hard to get this to where it is now. The current margin matches multicolumn. Otherwise, there will be two different margin sizes and I think consistency is more important. I can play around with it some more later--but I wouldn't bank on me being able to fix it.

**Comment by Controless** [comment]
Ah okay, understood. Thanks for the explanation!

**Comment by Alexendoo** [comment]
I would agree this is a bigger issue than having it in multicolumn for the points @Controless made about it targeting a larger set of users. But also mainly it creates a bad first impression, which is extremely important

**Comment by Nxt3** [comment]
How does this great a "bad impression"? This is such a small "issue".

I exclusively use multicolumn on my tablet--so I have to have a bad top margin there because more people use single column? As it stands--they are equal now.

**Comment by Nxt3** [comment]
I truly don't know why--but I was able to fix it this time; I tried this exact approach about a week ago--and it didn't work. Now it works. :| So there you go!

**Comment by Controless** [comment]
Unfortunately, this issue still isn't fixed and it looks the same as before on the latest alpha.
![screenshot_20160429-154549](https://cloud.githubusercontent.com/assets/13410769/14931596/8c65d3a0-0e21-11e6-8784-47100d0a1291.png)

**Comment by Alexendoo** [comment]
Still appears for me on b303c86fa2f78dbdb1e8fb44860d172e80e9755f, using a nexus 5

**Comment by Nxt3** [comment]
Show me a screenshot. There is just no way.

**Comment by Nxt3** [comment]
I think switching to a CoordinatorLayout messed it up. :|

**Comment by Alexendoo** [comment]
![image](https://cloud.githubusercontent.com/assets/1830331/14937595/1fd475e6-0f04-11e6-82f6-39a8d95b5570.png)
