### ISSUE TITLE
Thumbnails take up a very large portion of the card

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#1813]
Slide version: e6edda827e7ed361d0e107895c5f4dde77ffc4b0
Android version: 6.0.1

They're also now not square, which looks pretty weird

----

![](https://i.imgur.com/Dvesko1.png)

**Comment by Nxt3** [comment]
This is intended. Was to emulate this: http://i.imgur.com/JbnX82t.jpg

However, there is now a setting for Thumbnail size that works for any View Mode + Picture Mode.

**Comment by Nxt3** [comment]
Change line 254 of SettingValues to false for it to default to small thumbnails. Otherwise, it's an option and definitely fixed.

**Comment by Nxt3** [comment]
The thumbnail right margin was increased to match that of the title's left margin. It's not simpler to make a "list with big thumbnails". What I did was better because then it isn't tied to the view mode. I personally (and several others) like the larger thumbnail in cards view. If you don't want that, disable the setting for it.

**Comment by Alexendoo** [comment]
Right margin is fine it is the top I think is the main bit, if you look at the wide thumbnail it's a bit further down

**Comment by Nxt3** [comment]
Done. I added 8dp to the top margin. I agree--looks much better.
