### ISSUE TITLE
I'm able to view the user profile of someone else

### ISSUE THREAD

**Issue by baiddhruv** [ccrama/Slide#2151]
Slide version:5.4.3.5
Android version:7.0

I'm able to see someone else's profile with all upvoted, submitted comments etc. I get a connection error when I tap on it but I can then see the content

**Comment by Nxt3** [comment]
Is that not intended?

**Comment by baiddhruv** [comment]
It's not my profile I can view. Someone else's.

**Comment by Nxt3** [comment]
Yeah that's intentional. Go to a post, click on the overflow menu, and
select that user's name from the list of options.

**Comment by freundTech** [comment]
Public up- and downvotes is a reddit setting.

People can enable or disable if other people can see their up- and downvotes. You probably looked at the profile of a person who had it enabled.  
Can you check if you can see my (/u/freundTech)s up- and downvotes? They should be hidden.

**Comment by Georgiel** [comment]
I think they mean this btw. 

https://streamable.com/gchp

as in if you click the "My Profile" it takes one through to a different user.

**Comment by baiddhruv** [comment]
Yes that is it exactly! It is the same user as in the video as well.
Apologies if I was unclear.

**Comment by touzainanboku** [comment]
[Somewhat relevant](https://www.reddit.com/r/slideforreddit/comments/4yjc4d/bug_report_account_mishap_slide_just_logged_me_in/). I think it's being caused by the authentication issues that were/are being reported. Since ccrama reverted the changes in 5.4.3.6:

- logging out and logging back in
- backing up the settings, clearing the app's data and restoring the backup
- a reinstall

might fix it.

**Comment by ccrama** [comment]
@touzainanboku  is correct. Log out and back in and you'll be fine

**Comment by GeorgeWL** [comment]
@touzainanboku uninstall reinstall seemed to fix in my case
