### ISSUE TITLE
Gif not found

### ISSUE THREAD

**Issue by raazman** [ccrama/Slide#2212]
Slide version: 5.5 alpha 2
Android version: 6.0.1

Some gifs don't load and give the error: "Gif not found, converting the gif through gyfcat did not work."

I get this error multiple times a day and restarting or clearing app data does not fix it. It has been like this for many version of slide now and isn't seen in any other Reddit app. Here is an example post: https://reddit.com/r/interestingasfuck/comments/55ijht/combining_practical_effects_and_vfx/

**Comment by touzainanboku** [comment]
Slide uses Gfycat to convert any gif that's not from Gfycat or Imgur to a .mp4 file. Gfycat's API is currently broken, hence the issue. ccrama (the developer) has contacted Gfycat, and they've said they'll look into it. 

The reason other apps don't have this isprobably because either they don't use Gfycat at all, or they fallback to just showing the .gif when converting fails. I suggested the latter a while back, but ccrama said that it would complicate a lot of code. Since he's busy again with classes, it's probably unlikely that he'll implement it now. I still stand by my suggestion, but it's coming from someone with pretty much zero coding experience. I just hope Gfycat fixes it sooner, since I've basically stopped opening any gif that's not from Imgur or Gfycat.

**Comment by raazman** [comment]
Yeah I understand, but this may drive me to use sync or another app because every other post/comment is a gif nowadays.

**Comment by ccrama** [comment]
They said they are working on fixing it, really is nothing I can control

**Comment by touzainanboku** [comment]
> Why not just disable in app gifs and use the browser until it is fixed?

Because the built-in viewer is such a better experience :(

> That really isn't a reason to switch to using another app just to view content

I personally haven't switched to a different app, because IMO Slide does so many things right that other apps don't, but I do occasionally open non-Imgur/Gfycat gifs using a different Reddit app (at least when I feel like going through the trouble), so I don't find it that hard to imagine that some users, even if temporarily, might find this important enough to start using a different app. Especially if they browse a lot of gif-based subs. 

> gfycat assured that this was a one time thing and they are close to fixing it

That's great news, thank you for informing us. Still, I doubt it's guaranteed that it won't end up breaking again someday. I just think it's better if Slide had a backup solution that isn't reliant on an external service that's beyond your control. 

With all that said, I admit that everything I said above is without considering the difficulty of the coding involved, so I respect whatever decision you make. Thank you for your continuous hard work.

**Comment by ccrama** [comment]
It's a better experience when it works, but that's the only workaround
currently.

That being said I haven't seen a drop in users at all (it's actually
increased) so I don't see it as something crucial to make a workaround for.
That's why I decided to not spend the extra time to do this, especially
since it'll probably be fixed before I get the next update out anyway.

And thank you for understanding!

**Comment by touzainanboku** [comment]
I just happened to open a non-Imgur/Gfycat gif and it worked. Tried a few others. Also worked. It looks like it's fixed now.

**Comment by ccrama** [comment]
Yep seems to have just been fixed!
