### ISSUE TITLE
replace legacy apache with okhttp

### ISSUE THREAD

**Issue by marwanad** [ccrama/Slide#2250]
Currently, Slide add the legacy apache http as a dependency and it's only being used for the Synccit tasks. 

Replacing that with OkHttp (which is already included as a dependency) should save some bundle size and lead to much less verbose code. Okhttp provides transparent GZIP handling by default. In addition, using it would help get rid of the `Scanner` and `InputStream` and instead handle the JSON deserialization using responses using `ResponseBody.string()`. 

I can open a PR with the changes if that's of interest.

**Comment by Nxt3** [comment]
This would definitely be a big help. Feel free to open a PR. We just need to make sure to test it thoroughly.

**Comment by ccrama** [comment]
Really great find, I'd definitely be interested in getting this done (especially since it's only used in a small portion of the app)! OkHttp is definitely the better solution in this case.

If you would like to take a look, feel free to, and if you have any questions you can always drop by on IRC or let me know here

**Comment by ccrama** [comment]
Should be fixed with your PR #2251!
