### ISSUE TITLE
Use reddit's own mp4 version for i.redd.it gifs

### ISSUE THREAD

**Issue by touzainanboku** [ccrama/Slide#2316]
Slide version: 5.5.2
Android version: 6.0.1

So apparently gifs hosted on i.redd.it already have an mp4 version. For example, take [this](https://www.reddit.com/r/gifs/comments/5h99oy/quick_call_the_police_oh_nevermind/) post. If you look [here](https://www.reddit.com/r/gifs/comments/5h99oy/quick_call_the_police_oh_nevermind/.json) you can see this link:

https://g.redditmedia.com/tYxqLoegNeGZkkPnPEEqVl0slvI2Db0an1FwoSsIiMc.gif?fm=mp4&amp;mp4-fragmented=false&amp;s=565b17f08c922707bfd745cc1778a132

The link doesn't seem to work for me on desktop, but you can actually open it through Slide if you post it in a comment or something. You can even save it and open it with a video player. 

Now my request is for Slide to use this for i.redd.it links instead of relying on Gfycat. This will mean less waiting time for the user (no need to wait for Gfycat to convert the gif), and the app will be less reliant on Gfycat's API, so there won't be as many complains next time Gfycat's API stops working.

**Comment by ccrama** [comment]
That is only if the user has images for that subreddit enabled. If they don't, it won't have a link and would overcomplicate the system. I don't think we will implement this

**Comment by touzainanboku** [comment]
Oh, that seems to be the case. I didn't know. 

Still, not having to wait for conversion is really convenient, so I hope you consider adding it with Gfycat as a fallback.

**Comment by ccrama** [comment]
For the vast majority of gifs, Gfycat has already converted it and there should not be much waiting at all (50-200ms at MOST), so I don't think it would be much of an improvement to do so imho. Maybe one day if Reddit makes it a default part of the api

**Comment by touzainanboku** [comment]
Valid point. I did a bit of testing and gifs hosted on Imgur or Gfycat starting loading pretty much instantaneously or after 1~2 seconds at most, while i.redd.it ones that were already converted start loading after 2~3 seconds. I do agree that that difference isn't really noticeable. 

However, ones that weren't converted yet (at least I'm guessing they weren't cause I sorted by new) take about 7 seconds before starting to load. If loading from the .json file is almost as fast as loading ones hosted on Imgur or Gfycat, I'd say that would be a big improvement - at least in my case. But perhaps the same cannot be said for users with better internet connections. 

Either way, thanks for taking the time to respond. Would've been nice if it were part of the API by default.

**Comment by ccrama** [comment]
Actually Imgur and Gfycat already do mp4 conversion, so we don't do an
extra call on top of that. It's only non-imgur gifs that are converted
(which is why that system would be a little overkill).


On Dec 9, 2016 11:38 PM, "touzainanboku" <notifications@github.com> wrote:

Valid point. I did a bit of testing and gifs hosted on Imgur or Gfycat
starting loading pretty much instantaneously or after 12 seconds at most,
while i.redd.it ones that were already converted start loading after 23
seconds. I do agree that that difference isn't really noticeable.

However, ones that weren't converted yet (at least I'm guessing they
weren't cause I sorted by new) take about 7 seconds before starting to
load. If loading from the .json file is almost as fast as loading ones
hosted on Imgur or Gfycat, I'd say that would be a big improvement - at
least in my case. But perhaps the same cannot be said for users with better
internet connections.

Either way, thanks for taking the time to respond. Would've been nice if it
were part of the API by default.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ccrama/Slide/issues/2316#issuecomment-266180847>, or mute
the thread

**Comment by touzainanboku** [comment]
> Actually Imgur and Gfycat already do mp4 conversion

I know. I meant that ones that don't need conversion seem to start loading the fastest, with already converted non-Imgur/Gfycat gifs being almost as fast, while non-converted ones are the slowest.

**Comment by ccrama** [comment]
IMO the API is not yet mature enough to rely on, and if a user has thumbnails disabled for that subreddit, there will be no url returned in the API. If this becomes a standard part of the Reddit API in the future, though, I'd definitely reconsider using it
