### ISSUE TITLE
Hiding read posts stuck loading more posts

### ISSUE THREAD

**Issue by edde275** [ccrama/Slide#2381]
Slide version: 5.5.5
Android version: 7.1.1

When hiding read posts with action button, and it returns 5 results and needs to load more posts to fill the list, it gets stuck loading forever. Reading one of these five while it's still trying to load more, and then returning to the list of posts and refresh and hide read posts again and it will load more posts just fine.

**Comment by ccrama** [comment]
Unfortunately that is because of a limitation in the Reddit API. Only a certain amount of pages can be loaded after set time intervals, and if you hide all the posts trying to get more, the Reddit API will no longer return submissions. This is also the same reason we do not offer a setting to automatically hide read posts, as it would lead to this issue. Don't think there is a way to fix this, although after the request times out, it should say "No more submissions" at the top.
