### ISSUE TITLE
Imgur preview doesn't work for this gif. 

### ISSUE THREAD

**Issue by stevefye** [ccrama/Slide#241]
http://reddit.com/r/WTF/comments/3pzwv5/how_not_to_extinguish_a_fire/

**Comment by ccrama** [comment]
That is actually a feature to make sure you don't get very small or very blurry images in the previews. That being said, my app still hooks into the Preview API on Reddit to return images for almost all posts, so a few without it shouldn't be a dealbreaker, especially since they were hidden to make it look better overall. Did it revert to showing a thumbnail? You possibly have thumbnails disabled.
