### ISSUE TITLE
Night mode settings are 1 hour too early.

### ISSUE THREAD

**Issue by richiksc** [ccrama/Slide#2436]
Slide version: 5.6.1
Android version: 7.1.2

I set it to 6:00 but it ends at 7:00.

I think this has to do with daylight savings time.

**Comment by Nxt3** [comment]
Is this still an issue?

**Comment by richiksc** [comment]
@Nxt3 I can confirm that the issue still persists.

**Comment by PiwwowPants** [comment]
I am just asking, because maybe my boolean logic is bad, but it might be as simple as a bad conditional in the isNight method.

`return (hour >= nightStart + 12 || hour <= nightEnd) && tabletUI && nightMode;`

So, if the current hour is less than OR equal to the time you set to end night mode, it remains night mode. I am pretty sure dropping that OR equal will fix it. I want it to end when that hour hits.

Does that sound right?
