### ISSUE TITLE
Can't submit anything

### ISSUE THREAD

**Issue by moshpirit** [ccrama/Slide#2457]
Slide version: 5.6.1 (F-Droid)
Android version: 6.0.1

Since a few days I added another account but remove it after doing some testing. After that, I can't submit anything from Slide and need to use another app (RedReader is doing it for now) but I don't know why is this happening.

The message I get is:

`Ups! Something went wrong.   
Would you like to try to submit it again?`

**Comment by touzainanboku** [comment]
Fixed in 5.6.2.

**Comment by moshpirit** [comment]
Great! Thank you!

**Comment by KeronCyst** [comment]
Thanks for the notice, touzainanboku. I would sure hope it's fixed. I lost a lot of data due to this and am on the verge of going back to mobile-browsing on Chrome and uninstalling Slide, due to the issue of PMs not sending and then subsequently losing their text as well. I *really* hope auto-drafting before submissions gets included in a future update too.

**Comment by ccrama** [comment]
It does auto-draft @KeronCyst . Also the issue was caused server-side by Reddit and was not actually an issue with Slide, the update just includes a workaround for Reddit's issue
