### ISSUE TITLE
Copy Username option in Comment Reply

### ISSUE THREAD

**Issue by ccrama** [ccrama/Slide#2651]

**Comment by PiwwowPants** [comment]
I am looking at this a bit during breakfast-lunch.
`com.cocosw.bottomsheet` is really harshing my vibe because it does not accept a LongClickListener and the constructor access is package-private (using `@SuppressWarnings("WeakerAccess")` to ignore the weaker access from the Dialog class...) so I cannot extend it properly.

I am sure there is a way into this but unfortunately it's going to be annoying to go the long press route now.

**Comment by ccrama** [comment]
@PiwwowPants  What if we added an "author" icon to the reply menu and could instantly @ people? I think that would be convenient and we could extend it possibly for other people in the thread (a stretch goal though)

**Comment by PiwwowPants** [comment]
Who would we be "@"ing with this? The replyee, the OP of the comment chain, or the thread author? If that could be resolved I'd be all for making something "smarter". I was just going to make it a manual function so users could one-off copy names from any comment anywhere and use it.
 Your way would remove the obstruction of the BottomSheet though (though I really do think it should be replaced with the Android one...)

**Comment by ccrama** [comment]
I agree about the bottom sheet, but its use around the entire app would make it pretty difficult to change everywhere :/

As for @ing, it would be the person you are replying to, so the comment above you or submission if it's the first one!

**Comment by PiwwowPants** [comment]
Yeah. I have a functioning replacement for the vertical one already, but since some pieces use different buttons, I'd have to add some logic for setting up the right buttons (I'm just using the builder pattern so that's easy).
No matter what, the horizontal bottomsheet (the one with share image) is a problem because of the GridLayout. I don't really know how the current library did that. This is probably a project for another day though. I would support adding that to the reply.

Would you want it to be an icon or should it just be some sort of autocompletion (e.g., they start typing /u/). I don't know how complicated you want it but a single button that just populates in some text doesn't sound super great.

**Comment by ccrama** [comment]
Oh nice @PiwwowPants , if you need any help implementing that let me know!

For the horizontal layout, is it possible to just use a custom view for those buttons?

And autocomplete sounds a little more difficult than just an @ button, which I could probably get implemented pretty quickly

**Comment by ccrama** [comment]
Done!

**Comment by ccrama** [comment]
Would it be useful to have a button to copy the username from the submission itself? @PiwwowPants

**Comment by PiwwowPants** [comment]
I think that button should just end up in the bottom sheet as an "overflow" option, which leads me back to wanting it to be a long press. I don't know if adding more buttons to the bottom sheet.

I think I'm still confused though. Is "@"ing the person you're replying to a feature that people use? Replies already notify that user. Do people tend to "@" that person as well? I am not the heaviest Reddit user so I don't know all the use cases.

**Comment by ccrama** [comment]
That is true, which is why I was wondering more about a submission button vs something in comments.  I don't remember what spurred this issue but it wouldn't be hard to actually extend my last commit into a String array and include a list of all users above in the thread, along with a "draft"-like ui for showing them all. Could do it for the full 5.8 release as I've just pushed the next alpha

**Comment by PiwwowPants** [comment]
Yeah, I'm not really convinced on the "right" way to do this, which is why I was coping out and just putting it in the bottom sheet to long press the name to copy. I just don't know if that's discoverable enough. Long presses rarely are.

I think since no one is really pushing on this, and it's not like it's a "missing feature", it doesn't need to be really rushed. I would like to use it, but I just don't know the best way to go about it. The ideal is obviously typing /u/ and having a list of users in-thread to select from (not CRAZY hard to implement but still a chore). If you can think that that is possible that may be the best way to do it. It'd be fully user discoverable and the most convenient way possible to handle it.

**Comment by PiwwowPants** [comment]
https://github.com/ccrama/Slide/pull/2664

I put in the possibility of a Long press action in this PR. It's very early stages and will go through a lot of refactoring before it's merge-ready. But it's up and can possibly be ANOTHER way to do this (since adding this, I use it all the time)

**Comment by ccrama** [comment]
I implemented this with the ability to show all parent comment/submission comment OPs as well

**Comment by ccrama** [comment]
Pushing my local commits soon, lots of changes
