### ISSUE TITLE
Suggestion: Move "Guest" account from Account list to something else.

### ISSUE THREAD

**Issue by notyouraveragegithubuser** [ccrama/Slide#2745]
Slide version: any
Android version: all?

Hey, keep clicking on "guest" when switching accounts. It would be neat if it was under the Go Offline button or something.

Thanks!

**Comment by PiwwowPants** [comment]
[Quick fan fiction of this here.](https://imgur.com/a/w7oN32q)

There would be a bunch of logic to work around if we wanted to do this since it seems we're dynamically adding the Guest account to our list and checking which account is in use based on that. It could either be shimmed into place or rewritten. Both sound "fun"
