### ISSUE TITLE
Search and destroy instances drafts aren't saved when an API call fails

### ISSUE THREAD

**Issue by PiwwowPants** [ccrama/Slide#2778]
In a lot of cases (inbox messages), the user will not lose the content of the messages they send unless the message successfully sends. 

As noted in [this Reddit post](https://www.reddit.com/r/slideforreddit/comments/8kdvg6/save_draft_on_error/), there are instances the content is both not saved as a draft and the context (in this case, the comment reply dialog) is lost, leading to the users message from being lost. 

There are a lot of situations where we pass information up to Reddit as a post (and a POST 😀) where we need to guarantee nothing is lost on the client just because Reddit let us down. 

More of a project than a feature/bug report but scope is low so it's here.

**Comment by screwyluie** [comment]
This is the single most frustrating part of the app. I've lost so many messages at this point I'm ready to use another app entirely. I have to copy every inbox reply I make just in case it decides not to send it. Then I have to check the sent messages to make sure it actually went because sometimes it looks ok but the message never goes. Other times it'll fail and you're given two choices, I think they're cancel our use offline mode... Both options lose everything you typed so what's the point.

I'm tied of losing my replies, please fix this.

**Comment by Tensounder54** [comment]
@PiwwowPants Feel free to reopen this issue if you think I have made a mistake.
