### ISSUE TITLE
Notifications for posts/Subreddits not coming through. 

### ISSUE THREAD

**Issue by PiwwowPants** [ccrama/Slide#2841]
Report from [this Reddit post](https://www.reddit.com/r/slideforreddit/comments/92qfkx/subscribed_post_notifications_dont_notify_anymore/)

I've noticed this issue as well. When subscribing to subreddit updates, I don't get any notifications. I do seem to get notifications about messages coming in to me though.

I can't verify the report from Reddit easily, but it may be beneficial for others to verify that these notifications are no longer being pushed through.

**Comment by absolutez3** [comment]
I experience this well.

**Comment by abqnm** [comment]
I've posted this a few times over the past 6 months in the Slide sub (including the post you linked), and not once did I even get a response or acknowledgement from anyone associated with development — just a bunch of "me too" responses because it's affecting many people. 

Slide used to have the best support, but over the past 6 months, it feels like it's being abandoned. I hope this isn't the case, because Slide is the best reddit client for Android. I know Carlos has been focusing on iOS, but it seems like the Android version issues are being ignored entirely now.

I hope this can be fixed soon, because not getting sub notifications in subs with time sensitive content is quite frustrating.

Thanks!

**Comment by Tensounder54** [comment]
I've been trying to jump on a few of these issues recently. I'll take a look at it and see whats up.
