### ISSUE TITLE
MP4 videos are tagged as GIF files making it so you can't mute them

### ISSUE THREAD

**Issue by LeftHandedWave** [ccrama/Slide#2986]
Slide version: 6.0.1-3
Android version: 8.1.0 on LineageOS 15.1

I placed a request a few days ago (https://github.com/ccrama/Slide/issues/2979) but doing more troubleshooting it looks like it's an issue with MP4 videos incorrectly marked as GIF files.

Since it opens like a GIF file, there is no way to mute the video like any of the other video file formats.

**Comment by timawesomeness** [comment]
It's a known issue (which I've fixed in my local build, so it'll be fixed at some point in the future). What it actually does is shows the mute button for "direct" videos (i.e. mp4 or webm files that aren't from a host like imgur) regardless of audio content, and shows it for v.redd.it videos that contains audio.
