### ISSUE TITLE
Add support for Lemmy

### ISSUE THREAD

**Issue by PopeRigby** [ccrama/Slide#3053]
[Lemmy](https://github.com/dessalines/lemmy) is an open source, federated link aggregator, written in Rust. Lemmy is to Reddit as Mastodon is to Twitter. 

There is an issue going on in Lemmy's repository, that's talking about forking Slide for use as a client for Lemmy. I suggested we just add supoort in the existing Slide app, for convenience. Then you can just use the already existing account switcher to switch between your Lemmy and Reddit account.

I'll link to the issue on Lemmy's repository so people can talk between them: https://github.com/dessalines/lemmy/issues/151

**Comment by dessalines** [comment]
Lemmy dev here, so I'd just like to note that while it's not a drop-in replacement and doesn't match the reddit API exactly, the [Lemmy API](https://github.com/dessalines/lemmy/blob/master/docs/api.md) is fairly simple. I'm not sure if this means that it would be possible to abstract what does work for one and doesn't work for another, in the same code, or if a fork would be necessary.

**Comment by Nxt3** [comment]
It's already been stated numerous times that there are no plans to support Reddit alternatives in this app. It's too large an undertaking. Search the issues and you'll get responses from ccrama stating he didn't wanna do it.

**Comment by PopeRigby** [comment]
Alright. Sorry about that.

**Comment by Alexendoo** [comment]
No need to be sorry @PopeRigby, absolutely nothing wrong with asking.

It's just that reddit is so tightly coupled in Slide that supporting a different API would practically require a rewrite. We also carry a substantial amount legacy issues.

I would suggest that rather than forking it would actually be easier to create an entirely new app for Lemmy, with all the niceties of a new app ([Kotlin](https://developer.android.com/kotlin), [Jetpack](https://developer.android.com/jetpack), etc.). It would be quicker to get a basic demo app up and running that way, and ease ongoing maintenance significantly.

I'll add my comment to the Lemmy issue too.

Umbrella issue: #2823

**Comment by PopeRigby** [comment]
Thank you

**Comment by StaticallyTypedRice** [comment]
> 
> 
> Lemmy dev here, so I'd just like to note that while it's not a drop-in replacement and doesn't match the reddit API exactly, the [Lemmy API](https://github.com/dessalines/lemmy/blob/master/docs/api.md) is fairly simple. I'm not sure if this means that it would be possible to abstract what does work for one and doesn't work for another, in the same code, or if a fork would be necessary.

Somewhat related, but since Lemmy already uses a single-page web app that only makes API calls, could we not just package that up with Electron or something to get a basic app?

**Comment by Alexendoo** [comment]
@StaticallyTypedRice You'll want to take the discussion to lemmy's issue tracker since they probably won't be reading suggestions from here

Electron is for desktop, but there are similar things for Android
