### ISSUE TITLE
Submit post title could be multi-line, title included in preview

### ISSUE THREAD

**Issue by DocJava** [ccrama/Slide#3073]
Slide version: Android
Android version: 6.2.2
When submitting a post, the text input box is multi-line, but the title is single line only.
This makes sense in most cases but when you post on shower thoughts usually the line is a little long. 

When trying to preview a showerthoughts post (for example) it might display nothing because the title is not included. 

Requesting that the title is multiline for submitting a post, and that it is included in the preview display

**Comment by Tensounder54** [comment]
Titles are not multiline so this would be point less. We could set it so that titles wrap but that would bring the text out of line. There is potential to look into this as part of the Easter eggs scheme ( #309 ) for subs like [/r/aAskReddit](https://www.reddit.com/r/askreddit/) or, as you mentioned @DocJava, [/r/ShowerThoughts](https://www.reddit.com/r/showerthoughts).
