### ISSUE TITLE
Add ultra-compact view mode to see 6-9 posts at once (like Red Reader)

### ISSUE THREAD

**Issue by Victor239** [ccrama/Slide#3096]
Compare these two images of the same subreddit, the first from RedReader:
![](https://i.imgur.com/8Oh0jX1_d.jpg?maxwidth=640&shape=thumb&fidelity=medium)

The second from Slide:
![](https://i.imgur.com/8eF1l4v_d.jpg?maxwidth=640&shape=thumb&fidelity=medium)

Slide shows just 2 and a half posts whereas RedReader shows 6 (and when I scrolled further down the subreddit I even saw 9 posts at once at one point). 

Please make a view mode that shows more posts at once, I don't need single posts taking up such a huge chunk of the screen. I prefer to scan the headlines of a subreddit quickly and it's not easy on Slide compared to RedReader.

**Comment by Alexendoo** [comment]
The main difference is the large size of the font in Slide's case, you can reduce this though!

In `Settings → Font → Post font size` you've a few options to choose from.

There's also a few things you can play around with in the `Post layout` section that will affect the size, such as hiding the action bar

**Comment by AWalton** [comment]
Ah thanks! UI for that option could be made more obvious, it wasn't clear that it was a drop-down (at least when using AMOLED black). It could use some more spacing from the text above and below it, plus a downward pointing arrow to indicate that it's a dropdown menu. Perhaps a border as well. 

An option for a text size even smaller than Tiny would be nice. 

And the ability to put # of comments into the post content area which says the subreddit/time since posted/poster username. There's an option "show votes/comments in info line" which I thought might do it but it instead created a new line. But then I tried the "show content type in info line" option and it put the text in the aforementioned content area instead? It's not clear what the "info line" is in this case with these similarly named options having different effects.

**Comment by Tensounder54** [comment]
I feel like this is something that can be looked at in V2 as trying to implement this now could be a real challenge. As a further solution to what @Alexendoo has mentioned above, you could try reducing the system font size. On my Moto G4 running Android 7 that's `Settings > Display > Font Size` and you can also reduce the display size by going to `Settings > Display > Display Size`. Hope that helps! have a great day!

**Comment by Victor239** [comment]
This issue has been fixed for a while now at least with my settings.
