### ISSUE TITLE
Text selection

### ISSUE THREAD

**Issue by KaliK0t** [ccrama/Slide#315]
"Copy text" option for comments?

I can only Gild or share text but no copy

**Comment by The0x539** [comment]
I mean, one CAN share right onto the clipboard ¯\_(ツ)_/¯

**Comment by KaliK0t** [comment]
Doesnt work. It copies the permalink

Only way to copy text is samsung multiwindow drag and drop

**Comment by okungnyo** [comment]
Also:

1. Copy text from (self text) posts too, not just comments.

And:

(shamelessly copied from Reddit Sync's tracker: https://github.com/laurencedawson/reddit-sync-development/issues/1088)

2. Ability to selectively choose which part of the text you want to copy (for when you want to copy just one part of a huge post instead of the entire thing).

**Comment by ccrama** [comment]
Copy text from comments is fixed, copy text from selftext is not done yet

**Comment by ccrama** [comment]
Added copy for selftext
