### ISSUE TITLE
No audio on some v.redd.it videos.

### ISSUE THREAD

**Issue by jgammey** [ccrama/Slide#3196]
Slide version: 6.4
Android version: 11 Beta

Some v.redd.it videos do not play the audio. There is not even the mute icon if I tap the video to bring up the menu overlay. I noticed this change after upgrading to the Android 11 Beta.

The audio does play in a browser.

Example video: https://redd.it/hjb7gf

**Comment by LiquidZer0** [comment]
Redundant comment. Same issue marked #3204 . 

Android 9, Slide 6.4, Slide FRVP 2.5, Galaxy S8+, No root

Slide for Reddit Video Plugin (FRVP) hasn't seen an update since December 11, 2016, according to the play store. Videos seem random, varying threads. YouTube video links work fine. Only seems to affect v.redd.it links..
