### ISSUE TITLE
Revamp Settings

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#333]
Settings should be cleaned up before a beta release.

Right now, settings have icons beside some and not beside others (I'd prefer icons to not be beside any, because then it looks cleaner). There's no separators for in-between settings, and numerous other problems.

**Comment by ccrama** [comment]
Please be more specific. I have icons only on the main settings (per material guidelines) and it is split up like it should be.

**Comment by alexsmithfanning** [comment]
On the general settings, the topmost settings don't have a subtitle and they have an icon next to them, which isn't required nor do I think is needed.

The bottommost settings are separated by first a separator, then the subtitle. While the separator should be between each individual setting.

Another thing I didn't mention: on the white theme, the settings background is a weird gray color. It should be white.

**Comment by ccrama** [comment]
I see your point about general settings, will look into it.

And the gray color is the material spec color for activity backgrounds (including settings). It looks too glaring as white, and cards are supposed to be the white objects

**Comment by alexsmithfanning** [comment]
Sorry, not white. Light gray.

Cabinet: https://goo.gl/VYMQSH

Twidere: https://goo.gl/p5CK02

Amaze: https://goo.gl/fhUJWm

Inbox: https://goo.gl/2xeAXx

The only one of those that is different in any way is Cabinet.

Then Slide: https://goo.gl/GqfdtH

Slide is much too dark.

**Comment by ccrama** [comment]
My app looks almost exactly like Twidere, which also follows Material spec. And the spec says use icons if you use it for everything, which I do (just like Settings in stock Android as well)

**Comment by alexsmithfanning** [comment]
Those are categories though. Twidere has many more settings than Slide does, so its justified. They're also separated by separators and subtitles too. The icons are there because they can be, and it looks good.

Did you take a look at Amaze, Inbox, and Cabinet? They all have a slightly lighter color of gray, including Twidere.

For example, Twidere's background color (in hexadecimal) is #EEEEEE while Slide's background is #D2D2D2. The specification says that it should be #EEEEEE.

**Comment by ccrama** [comment]
Ah yeah forgot I fixed the color in the latest version (pushing to play store tomorrow). And as for the settings, yes the icons do belong there. The spec says nothing about having icons or not, but personally I like the icons because it gives a quick glance at what the setting will do, and because of this I'm keeping it. As for general settings, though, I'll work on reorganizing it!

**Comment by alexsmithfanning** [comment]
Sorry to beat the already dead horse, but other things need changing too.

Card backgrounds colors are wrong, and splash screen colors are wrong too.

**Comment by ccrama** [comment]
Any activity background is wrong for you (because of the wrong value), but is fixed internally. And the card backgrounds are #ffffff, which is [material](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bx4BSt6jniD7WVQ2WXFLeUtxSlE/style_color_themes_light2.png)

**Comment by alexsmithfanning** [comment]
Well crap. Showed me.

**Comment by l3d00m** [comment]
merge into #372
