### ISSUE TITLE
Minify on compile?

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#337]
Would compressing (minify) the code before compilation improve performance at all? I know with HTML and CSS the more it gets minified the faster it loads. Is the same true for Java?

I'm not talking about making the entire source code hosted on GitHub like that, just the code right before compilation.

**Comment by Alexendoo** [comment]
It does not, it is compiled to a binary not plaintext such as HTML/CSS.

For the HTML/CSS it only loads faster due to a reduced filesize meaning the transfer takes less time, it wouldn't make a difference here (if it were applicable) due to the files already being stored locally, they need only be downloaded once.

**Comment by alexsmithfanning** [comment]
Ah, okay. Thanks!
