### ISSUE TITLE
Using fix String(Client-ID) as authorization header value

### ISSUE THREAD

**Issue by cyxin577** [ccrama/Slide#3397]
Slide version: 6.7.1
Hi, 
I find the HTTP request set the fixed Client-ID as the authorization header in some class (e.g., UploadImgurAlbum.java). May it be hijacked? I think the auth token should be generated using some encryption algorithms by server side? Do you confirm this bug? Thank you.
![图片](https://user-images.githubusercontent.com/69659437/124900220-719c4800-e013-11eb-999c-45b9dc4a428d.png)

**Comment by cyxin577** [comment]
Thanks for reply! I found there are several similar discussions about the plain text token and always without a good answer. Maybe there is a better way to make it more secure.

**Comment by Alexendoo** [comment]
Note that it's not a security problem as such, client ids aren't used for authorizing requests for reading/modifying user data. As an example Slide still has a client ID for reddit, but to authorize actions it receives a per user token during the sign in process (using OAUTH)

The client IDs are only used for things like ensuring a single app doesn't make too many API requests, e.g. a limit of 10,000 requests/month. It's like a User-Agent header but assigned by the service rather than decided by the client

**Comment by cyxin577** [comment]
I see. Thanks for your explain!
