### ISSUE TITLE
Punctuation in strings

### ISSUE THREAD

**Issue by c727** [ccrama/Slide#362]
Do you really want to delete settings for /r/

Expect something like this:
Do you really want to delete settings for /r/$string?

Cause in german it would be:
Möchtest du die Einstellungen für /r/$string wirklich löschen?

**Comment by ccrama** [comment]
Good find! Will do this, thanks

**Comment by l3d00m** [comment]
I think there are some more strings that have this problem, I will see if I can find more strings.

**Comment by c727** [comment]
@l3d00m
You are right, translation files need some rework:
-add punctuation character to all sentences not only some
-some phrases, eg the check mail frequency., have 1 placeholder for 2 phrases. this is a bit confusing when there is no (english) example sentence so I have to look for it in the APP first. Or maybe make 2 placeholders instead.
-there are around 5 similar pharses why I should donate. - do wie really need this?
-a few strings are full uppercase. This should be handled by the APP and not the translation file
-english file has some phrases missing. I also mentioned this in the commit yesterday

**Comment by l3d00m** [comment]
Thanks for all the feedback! 

1. That's a good idea, we should use no punctuation or punctuation for all sentences (@ccrama pls)  
2. I haven't noticed that yet but I will fix it with two placeholders. I will also add some Screenshots and example sentences to crowdin over the next days. 
3. It was a bit complex to use one string with a Placeholder instead of two strings because it has different colors within the string. I will look into it again and see if I can simplify it. 
4. That's already done for most strings, I just forget to make them lower-case in the strings.xml
5. I answered there.

**Comment by l3d00m** [comment]
Only thing missing is the punctuation

**Comment by ccrama** [comment]
Long time coming, should be fixed now though!
