### ISSUE TITLE
When swiping through posts, there is a dead end and no more load

### ISSUE THREAD

**Issue by 2fst4u** [ccrama/Slide#478]
When swiping through posts (say, on the front-page where I know they're infinite) I will often get to a dead end after about 20-50 (haven't counted) to what I presume is the last post cached.

Somehow the next posts need to be preloaded to fix this and allow me to continue swiping.

This can be sometimes temporarily solved by backing out to the sub, then going back into the last post I saw

**Comment by l3d00m** [comment]
A 'load more posts' at the bottom should do the trick, at least as a workaround.

**Comment by 2fst4u** [comment]
Sorry I know the correct verb would be "swiping" too but autocorrect got the better of me

**Comment by l3d00m** [comment]
No problem, it's possible to edit titles!

**Comment by 2fst4u** [comment]
Couldn't figure it out on mobile but I admittedly didn't look very hard lol

**Comment by l3d00m** [comment]
Yeah, the mobile page is pretty useless. I'm on mobile right now too and I always use the desktop version.

**Comment by 2fst4u** [comment]
To add to this, this happens in the immersive mode also, which is quite annoying and detracts from the experience.

**Comment by Deadleg** [comment]
I've been working on this for the last few days and I am nearing a solution. You can now slide continuously to the end in subreddits and multireddits, however I need to test this further, plus further refactoring needs to be done to fix other potential bugs. Once this is done, #753 should be pretty easy to fix.

I don't think I've broken too much since it's 90% cutting and pasting code around, but it's hard to tell without testing.

Progress can be seen here: [deadleg/refactor/submissionloading](https://github.com/Deadleg/Slide/tree/refactor/submissionloading)
