### ISSUE TITLE
Make the navigation drawer follow Material's guidelines towards multi-account

### ISSUE THREAD

**Issue by angrybakon** [ccrama/Slide#541]
This is not fully documented but here are the specs: https://www.google.com/design/spec/patterns/navigation-drawer.html#navigation-drawer-content.

I switch accounts a lot and Slide is not usable in my case for now. I'm looking at the Android Play Store application for reference:

- Top left is the current account, bigger fab
- Top right are the others accounts, smaller fab
- One tap on one of the other accounts and the fabs will be swapped, animated both in position and size

Furthermore, the Play Store application isn't restarted when switching account as opposed to Slide.

**Comment by l3d00m** [comment]
this sound really good

**Comment by The0x539** [comment]
FYI, those circles are only FABs as much as contact photos are. They're neither floating nor buttons, really.

**Comment by angrybakon** [comment]
@The0x539 Thanks for the clarification :)

@okungnyo Mmh I don't know about Relay, but until Slide requires less actions (4) to switch account, I'd rather use Sync which requires 3 and doesn't completely reload the application :). I don't know how much work this demands from what is already implemented but I like the fact that with Material guidelines it would require only 2 actions to switch accounts. 

I can provide a GIF of what I mean with the transitions and all from a Web based project I've worked on if necessary :)

**Comment by l3d00m** [comment]
Leaving this here https://github.com/mikepenz/MaterialDrawer#screenshots

**Comment by alexsmithfanning** [comment]
[What about this?](https://plus.google.com/photos/104366200511123430141/album/6222696728935300001/6222696728833764562?authkey=CMOAtaXhxtCLzQE&sqid=100681783215868345226&ssid=152f4fe6-410d-4a49-b3e2-4062623254b0)

Don't know if anybody here knows about this, so I'm just gonna slap it here.

**Comment by ccrama** [comment]
@angrybakon  I actually like having the account switcher in the header more, that's a good idea. Will also be adding a way to switch accounts from the submit screen and the comment screen :)

As for restarting, that is a necessity because Slide has to re-authenticate with new credentials, but that will be lessened with the new offline capabilities in slide  (basically a .8 second restart time)!

**Comment by alexsmithfanning** [comment]
What about this?

![New drawer design](https://lh3.googleusercontent.com/gmyDkB-ph1ZA-pmzJ3v7qGISp1KCWKQhV4gkj4iNdXI=w1440-h900-no)

And this?

![New account manager](https://lh3.googleusercontent.com/KurhQupXeE_laH8_Sco24wNrWfp5rVIow7kU1_VxR10=w1440-h900-no)

I don't know how many people know about this here, so here you go.

**Comment by ccrama** [comment]
I like your idea, but I think having the account switcher there is a better use of space than having the profile items under the header. I also think subs should be at the bottom for easier reaching, and the current buttons are fine because you don't have to scroll to get to settings, while in your mockup you would have to either A) tap subs every time you want to go to a sub or B) tap to close subs to scroll and tap on settings. 

I'd also rather not change up the UI drastically as it works fine the way it is right now, and this account switcher makes sense with the current layout

**Comment by alexsmithfanning** [comment]
Just another note: I'm pretty sure the navigation drawer items aren't spaced correctly from the edge. If you compare screenshots of my mockup, and a screenshot of Slide, then mine is much closer to the left edge of the screen than yours is. I *know* for a fact that my metrics are correct.

Did you perhaps make it 32dp away from the edge rather than 16dp?

**Comment by ccrama** [comment]
Nope, it's actually 10dp in slide

**Comment by alexsmithfanning** [comment]
What? That doesn't make any sense. If anything the number should be *too big*.

It is wrong though, right? Or is it just on my screen size?

**Comment by l3d00m** [comment]
it's 26dp

**Comment by alexsmithfanning** [comment]
The top is like that too. It should also be 16dp @ccrama.

**Comment by l3d00m** [comment]
Which top do you mean @alexsmithfanning?

**Comment by alexsmithfanning** [comment]
Top padding, at the top of the navigation drawer. It also appears the bottom padding is wrong too.

**Comment by l3d00m** [comment]
#714 should fix the space things you mentioned @alexsmithfanning

**Comment by l3d00m** [comment]
A multi account switcher similar to this was implemented in v4.6.

**Comment by ccrama** [comment]
Has been done, yes
