### ISSUE TITLE
"Hidden" section of profile, with a way to unhide.

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#569]
Displaying stuff hidden via reddit, not app-specific transient hide.

**Comment by okungnyo** [comment]
I have a couple of related suggestions:

1. (tiny cosmetic issue) Rename [Saved posts] in the navigation drawer, because it includes comments too, not just posts.

2. Add a **[Downvoted] section under your profile.** There is [Upvoted posts] in the navigation drawer, but no [Downvoted posts].

3. (tiny cosmetic issue) When you click [Upvoted posts], the action bar says "Liked" instead of "Upvoted".

**Comment by l3d00m** [comment]
Why do you think this is high priority?

**Comment by The0x539** [comment]
Because currently you can reddit API hide, but you can't unhide without the
website or another app.

**Comment by okungnyo** [comment]
Guys, I just noticed Slide doesn't even have the ability to hide posts at all.

Would be pretty weird to have the ability to *unhide* posts when you can't even *hide* them in the first place.

Start a new issue or will @l3d00m append it to this one?

**Comment by l3d00m** [comment]
It is possible, activate the fab in settings.

**Comment by Alexendoo** [comment]
It's in the overflow menu on posts in subreddit view, but not when directly viewing the post

**Comment by okungnyo** [comment]
@l3d00m A way to hide posts for users who hate FAB and have it disabled, then?

@Alexendoo Huh, well that's certainly an annoying inconsistency. Will the two menus be unified (so they are the same) in the next version?

**Comment by Alexendoo** [comment]
It isn't done yet as far as I know, but I think it should be

**Comment by l3d00m** [comment]
@okungnyo it's possible to put the button in the submission action bar
