### ISSUE TITLE
Settings cosmetic issues

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#573]
* Text wraps unnecessarily
* There appears to be two touch targets going on
* The done button spans the entire dialog, should be on the right hand side

![](http://i.imgur.com/VpSMYZu.png)

![](http://i.imgur.com/gvT5j5Y.png)

![](http://i.imgur.com/G4PzDqy.png)

**Comment by l3d00m** [comment]
The first one is fixed on the 'setting_rework' branch, it was just a '/n' in the string.

**Comment by l3d00m** [comment]
Uh, I didn't know that it's already branched into master. 

The second one is also happening for default sorting and font size.

**Comment by okungnyo** [comment]
Also shouldn't it just be "Notifications"?

"Notification Settings" seems redundant.

**Comment by l3d00m** [comment]
True, same with the other titles.

**Comment by okungnyo** [comment]
Oh, just checked the latest version, it has already been changed, it is ]Notifications].

But the other ones [Subreddit Theme Settings] and ]Floating Action Button Settings] haven't been change dyet.

**Comment by okungnyo** [comment]
Capitalization inconsistencies throughout the app:

"Text Text" should be "Text text".

Action bar

* Choose a Sorting Type --> Choose a sorting type
* Top This Hour --> Top this hour
* Top Today --> Top today
* Top This Week --> Top this week
* Top This Month --> Top this month
* Top This Year --> Top this year
* (same for Controversial)

In a post

* Choose a Sorting Type --> Choose a sorting type

Navigation drawer:

* Go to profile > Enter Username --> Go to profile > Enter username

...and so on (there's too many in [Settings] for me to list here).

But the general rule to follow is: only capitalize the first letter, don't capitalize the rest, unless it's a name, like "Multi-Column" or "Buy Pro".

**Comment by okungnyo** [comment]
Also, I just noticed that reddit.com uses "past" instead of "this":

* this hour --> past hour
* today --> past 24 hours
* this week --> past week
* this month --> past month
* this year --> past year

**Comment by okungnyo** [comment]
I found the Material Design page regarding capitalization: https://www.google.com/design/spec/style/writing.html#writing-capitalization-punctuation

Apparently it's called "sentence-style caps".

**Comment by okungnyo** [comment]
The whole page is worth checking out, actually.

**Comment by okungnyo** [comment]
Just making sure, but has every user-facing text string been corrected with sentence-style caps?

**Comment by okungnyo** [comment]
I found many inconsistencies that have cropped up in 4.5, I will post them if you promise to fix them @l3d00m 

(Yes, I live to make your life harder heh...)

**Comment by l3d00m** [comment]
Feel free to post them, but I can't promise you that I can fix everything :p

**Comment by okungnyo** [comment]
First, everything should be sentence-style caps: https://www.google.com/design/spec/style/writing.html#writing-capitalization-punctuation

So for example:

* [Go to profile > Enter Username] should be [Go to profile > Enter username]
* [Link Handling] should be [Link handling]
* [Main Theme] should be [Main theme]
* [Backup & Restore] should be [Backup & restore]
* [Report Bugs] should be [Report bugs]
* ...and so on.

For everything. Every user-facing string/text.

Second, [Go to profile] should be renamed to [Go to user] because reddit.com itself uses "user" and not "profile".

Third, [Settings]:

* [General Settings] should be [General]
* Add a description for [Swipe away from anywhere] because I still don't understand what it does exactly, and I'm sure I'm not alone...

If you can fix these, I will post more as a treat.
