### ISSUE TITLE
Support for spoilers

### ISSUE THREAD

**Issue by silentkun** [ccrama/Slide#692]
Subreddits such as /r/anime uses spoiler tags which do no show inside the comment.

**Comment by Deadleg** [comment]
Pull request #705 added support, just needs testing. I referenced this issue in the pr but it didn't link >_>

**Comment by l3d00m** [comment]
@deadleg I would have closed this, but spoilers don't work for me unfortunately. Clicking on the back Spoiler box does nothing, as well as clicking on the seperate link (that shouldn't be there). It no longer crashes though.

**Comment by Deadleg** [comment]
Oh that's new, I'll investigate.

At the moment clicking on the black text doesn't do anything because it interferes with the normal onClick behaviour of posts, and it also makes it impossible to have links within spoilers (though I can't find any example of links within spoilers atm so it'll break anyway). It also makes it harder to accidentally reveal spoilers if that's much of a problem.

The link is there because Sync does a similar thing where the unhidden text is a link, and the spoiler is boxed out. Though reddit is fun just has the spoiler text blocked out, no links. However you can't hide spoilers because of this.

I'm a fan of the former, since it highlights what is spoiled (it could do with better styling however) e.g. https://www.reddit.com/r/asoiaf/comments/i2mg6/attention_we_now_have_a_new_spoilertagging_system/

**Comment by l3d00m** [comment]
It works now, thanks @Deadleg! 

FYI: If you want to close a issue with your pr automatically, you have to write either 'fix #issuenumber' or 'fixes #issuenumber' in your pr description or in your commit description.
