### ISSUE TITLE
"which link would you like to share?" prompt shown for self posts

### ISSUE THREAD

**Issue by abraham** [ccrama/Slide#776]
If there is no content URL, it would be nice if this prompt was skipped.

![screenshot_20160113-081348](https://cloud.githubusercontent.com/assets/3341/12302468/ed8865d4-b9ea-11e5-825d-6238559c763f.png)

**Comment by okungnyo** [comment]
Nice catch.

**Comment by okungnyo** [comment]
Also I just noticed this, but those icons seem a bit out of place.

* a bookmark icon next to an 'r/...' link
* a star icon next to an [Open in browser] button
* an info icon next to a [Copy text] button

Were these icons chosen because choosing the obvious ones (browser icon for [Open in browser] and copy icon for [Copy text] would draw accusations of copying from the other Reddit apps?

**Comment by ccrama** [comment]
@okungnyo  They were probably chosen because they were icons already in slide that didn't need to take up more room in the apk, has nothing to do with accusations and I highly doubt anyone would accuse us of copying if we used the same icons

**Comment by okungnyo** [comment]
Ok, just seemed out of place is all.

**Comment by l3d00m** [comment]
The info again was more like a placeholder and the star icon is still there because the string was 'give gold' a while ago.

**Comment by okungnyo** [comment]
@l3d00m 

Sounds like you don't like it either and want to have it changed too?

**Comment by l3d00m** [comment]
Yeah, it should be changed, but I don't think it has priority right now.

**Comment by okungnyo** [comment]
Yeah
