### ISSUE TITLE
Shouldn't internal browser vs. Chrome Custom Tabs be radio options instead of checkboxes?

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#792]
Don't they conflict? Shouldn't it be one or the other?

And they are both enabled by default, which doesn't make sense.

**Comment by Alexendoo** [comment]
There are essentially three options which could be used with radio buttons yeah:

- Open in chrome custom tabs
- Open in a webview
- Open in an external browser

The custom tabs slider when disabled means use a webview instead, the internal web browser toggle when disabled means open externally, this disables the customtabs slider. I think there are a few cases like this where radio buttons may be preferable in the settings, which as a whole is being looked at quite closely currently

**Comment by okungnyo** [comment]
I understood absolutely none of what you said, sorry dude lol

**Comment by Alexendoo** [comment]
Right so there are two sliders that govern what happens when you open a "normal" link in slide, an article for instance rather than a gif/video/album. They are `Internal web browser` and `Use Chrome Customtabs`. There are three possible states currently to be in:

##### Custom tabs

`Internal web browser`: On
`Use Chrome Customtabs`: On

This use [Chrome custom tabs](https://developer.chrome.com/multidevice/android/customtabs) which bring a few differences, though they may not all be exploited currently in slide such as the preresolution of domain names/preloading.

![](http://i.imgur.com/ziK2nLB.png)

##### Webview

`Internal web browser`: On
`Use Chrome Customtabs`: **Off**

It's also possible to use a standard webview in place of Chrome custom tabs, this may be preferable for a couple reasons but the ones I'm aware of are that it doesn't fall back to an external browser if you don't use Chrome, and that history is not shared with your normal Chrome profile.

![](http://i.imgur.com/TN7YLgK.png)

##### External browser

`Internal web browser`: **Off**
`Use Chrome Customtabs`: Either on or off

This is the fairly well known open in your default browser externally, be that standard chrome, firefox, etc.

--------

There is some redundancy here in two ways, though we have three states there are options that may imply there are four outcomes (two switches, either can be on or off). 

In addition since chrome custom tabs uses an ACTION_VIEW intent it does fall back (if say you don't have chrome as your default browser, or installed at all) to that browser rather than a webview, this to me means we only really need two options, Chrome custom tabs or webview

**Comment by okungnyo** [comment]
+1 to everything you said, so three radio options? Internal browser, Chrome Custom Tabs, and external.

**Comment by Alexendoo** [comment]
I think there's one thing that needs to be found out, which is are there many people using chrome but as an external browser and not custom tabs, I suspect the answer here is no since they're so similar. 

If it isn't the case then we can just have one option, called `Use webview` or something along those lines, which when off will use chrome custom tabs if your default browser is chrome, or whichever browser you've chosen. However if you turn it on a standard webview is presented.

**Comment by Alexendoo** [comment]
Merge into #1128
