### ISSUE TITLE
transparent overlays for media 

### ISSUE THREAD

**Issue by perler** [ccrama/Slide#815]
I like how relay pro handles media players like youtube or gifs: 
![16 january 2016 191537 cet](https://cloud.githubusercontent.com/assets/623092/12373776/96a0c9b2-bc85-11e5-8dfa-601fc35968f9.jpg)

any chance seeing this in a future release? It makes the experience more fluid IMO. also the "close on touch" feature is better than the current back button.

**Comment by Alexendoo** [comment]
That would be quite nice, for exiting if you have swipe from anywhere (or whatever that setting is called, it's under general) it's a pretty nice way to exit, just swipe it to the left

**Comment by okungnyo** [comment]
+1 for transparent overlays.

I was wondering why I was having such a hard time adjusting to Slide.

And it was the transparent overlays!

That was it!

My routine had become: while waiting for the GIF to load, read the title of the next post.

But Slide doesn't have transparent overlays, so there is nothing to look at.

That's why the wait for the GIF loading felt so much longer.

@ccrama @l3d00m what do you guys think?

**Comment by ccrama** [comment]
@okungnyo  I don't like transparent overlays (hence why Slide doesn't have them), but would it be better if the title of the submission was on the gif or image page?

**Comment by ccrama** [comment]
Never mind I liked it. Done in latest commit!

**Comment by okungnyo** [comment]
So we can skim the titles of the other posts while waiting for the GIF to load now?

**Comment by ccrama** [comment]
Yes

**Comment by okungnyo** [comment]
Man of little words

**Comment by ccrama** [comment]
Yes
