### ISSUE TITLE
Think of some better category names

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#846]
The [Other] section is too crowded and filled with stuff that have nothing to do with each other.

**Comment by Alexendoo** [comment]
I think it's the biggest remaining issue with settings, it's not easy to know where you want to be to find a setting without learning the layout:

The appearance section is pretty decent since it does what it says mostly, though some appearance things are still dotted throughout other categories. There are also a large number of non aesthetic changes in the comments section particularly (FAB, actions)

However the remaining 12 entries are in either "general" or "other", which don't actually give you any information, the distinction is mostly arbitrary. It's particularly tricky with Slide since there are just so many options.

**Comment by ccrama** [comment]
I did a lot of reorganization the last few updates, is this still a big issue?

**Comment by Alexendoo** [comment]
It's quite a bit better now, if I think of any other tweaks I'll open something new as I don't have anything to suggest on hand
